### NumPy basics

In [3]:
import numpy as np

### Creating array from list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("2D array: ", array_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs numPy array

In [8]:
py_list = [1, 2, 3]
print("python list multiplication ", py_list * 2)
# In numpy multiply always works on element
np_array = np.array([1, 2, 3])
print("NumPy array multiplication: ",np_array*2)

import time
start = time.time()
np_array = np.arange(1000000)
print("\n NumPy operation time: ", time.time()- start)

python list multiplication  [1, 2, 3, 1, 2, 3]
NumPy array multiplication:  [2 4 6]

 NumPy operation time:  0.005190372467041016


### creating array from scratch

In [ ]:
# create a zero value array
zero = np.zeros((3, 3))
print("zeros array: ", zero)

#creating a one value array
ones = np.ones((2,3))
print("one array: ", ones)

# creating contant vlaue array
con = np.full((2,2), 5)
print("constant value array: ", con)

# creating random value array
random = np.random.random((3,3))
print("Random value array: ", random)

# creating squence array
sequence = np.arange(0, 10, 2)
print("array of sequence: ", sequence)

zeros array:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
one array:  [[1. 1. 1.]
 [1. 1. 1.]]
constant value array:  [[5 5]
 [5 5]]
Random value array:  [[0.08846919 0.21505491 0.66199849]
 [0.16234682 0.31370443 0.87153132]
 [0.30696678 0.83845182 0.60838655]]
array of sequence:  [0 2 4 6 8]


### Vector, Matrix, Tensor

In [20]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [2,3]],
                   [[4, 5], [6,7]],
                   [[8, 9], [10, 11]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:  [[[ 1  2]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


### Array Properties

In [21]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim )
print("Size: ", arr.size)
print("Data type: ", arr.dtype)

Shape:  (3, 3)
Dimension:  2
Size:  9
Data type:  int64


## Array Reshaping

In [28]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped Array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transpose array: ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
