# NumPy Operations

In [2]:
import numpy as np

In [17]:
arr = np.arange(11)
print(arr)
print("Basic Slicing: ", arr[2:7])
print("with steps: ", arr[1:8:2])
print("Negtive indexing: ", arr[-3])

[ 0  1  2  3  4  5  6  7  8  9 10]
Basic Slicing:  [2 3 4 5 6]
with steps:  [1 3 5 7]
Negtive indexing:  8


### 2D Array

In [6]:
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Specific element: ", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Enitre column: ", arr_2d[:,1])

Specific element:  6
Entire row:  [4 5 6]
Enitre column:  [2 5 8]


### Sorting

In [14]:
unsorted = np.array([3, 5, 2, 9, 7, 1, 8, 4])
print("Sorted array: ", np.sort(unsorted))

unsorted_2d_arr = np.array([[3, 1], [1, 2], [2, 3]])
print("2D array: ", np.sort(unsorted_2d_arr))

# sort 2d array by column
print("Sorted 2D array by column: ", np.sort(unsorted_2d_arr, axis=0))

# sort 2d array by row
print("Sorted 2D array by row: ", np.sort(unsorted_2d_arr, axis=1))



Sorted array:  [1 2 3 4 5 7 8 9]
2D array:  [[1 3]
 [1 2]
 [2 3]]
Sorted 2D array by column:  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row:  [[1 3]
 [1 2]
 [2 3]]


### Filter

In [18]:
numbers = np.arange(11)
print(numbers)

even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: ", even_numbers)

# Filter with mask
mask = numbers > 5
print("filter using mask: ",numbers[mask])

[ 0  1  2  3  4  5  6  7  8  9 10]
Even Numbers:  [ 0  2  4  6  8 10]
filter using mask:  [ 6  7  8  9 10]


### Fancy indexing VS np.where()

In [23]:
print(numbers)
indices = [0, 2, 4]
print(numbers[indices])

# np.where(expression) -> gives matched indices
where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])


[ 0  1  2  3  4  5  6  7  8  9 10]
[0 2 4]
(array([ 6,  7,  8,  9, 10]),)
NP where [ 6  7  8  9 10]


In [33]:
condition_array = np.where(numbers > 5, numbers,  numbers*2)
print(condition_array)

[ 0  2  4  6  8 10  6  7  8  9 10]


### Adding and removing data

In [40]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)


[1 2 3 4 5 6]


In [42]:
# for 2D arrays
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("original array:", original)
print("with new row", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("original array:", original)
print("With new column", with_new_col)

original array: [[1 2]
 [3 4]]
with new row [[1 2]
 [3 4]
 [5 6]]
original array: [[1 2]
 [3 4]]
With new column [[1 2 7]
 [3 4 8]]


In [44]:
# Delete an element from an array
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]


### Array compatibilty

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatiblity of shapes", a.shape == b.shape)

Compatiblity of shapes False
